Added a readme note to install istanbul
Got a small hiccup during installation, added a readme note to install a formal dependency

```
ॐ  ~/development/frontend topic/js-code-coverage ☠ ember install ember-cli-code-coverage
Yarn: Installed ember-cli-code-coverage
Cannot find module 'esprima'
Error: Cannot find module 'esprima'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/kyle/Development/frontend/node_modules/istanbul/lib/instrumenter.js:11:24
    at Object.<anonymous> (/home/kyle/Development/frontend/node_modules/istanbul/lib/instrumenter.js:1097:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
Could not register command from file cover.js
Error: Could not register command from file cover.js
    at /home/kyle/Development/frontend/node_modules/istanbul/lib/util/factory.js:60:27
    at Array.forEach (native)
    at Object.loadStandard (/home/kyle/Development/frontend/node_modules/istanbul/lib/util/factory.js:53:29)
    at Object.<anonymous> (/home/kyle/Development/frontend/node_modules/istanbul/lib/register-plugins.js:12:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
ॐ  ~/development/frontend topic/js-code-coverage! ☠ npm install -g istanbul
/home/kyle/.nvm/versions/node/v6.11.1/bin/istanbul -> /home/kyle/.nvm/versions/node/v6.11.1/lib/node_modules/istanbul/lib/cli.js
/home/kyle/.nvm/versions/node/v6.11.1/lib
└─┬ istanbul@0.4.5 
  ├── abbrev@1.0.9 
  ├── async@1.5.2 
  ├─┬ escodegen@1.8.1 
  │ ├── estraverse@1.9.3 
  │ ├── esutils@2.0.2 
  │ ├─┬ optionator@0.8.2 
  │ │ ├── deep-is@0.1.3 
  │ │ ├── fast-levenshtein@2.0.6 
  │ │ ├── levn@0.3.0 
  │ │ ├── prelude-ls@1.1.2 
  │ │ └── type-check@0.3.2 
  │ └─┬ source-map@0.2.0 
  │   └── amdefine@1.0.1 
  ├── esprima@2.7.3 
  ├─┬ glob@5.0.15 
  │ ├── inflight@1.0.6 
  │ ├── inherits@2.0.3 
  │ ├─┬ minimatch@3.0.4 
  │ │ └─┬ brace-expansion@1.1.8 
  │ │   ├── balanced-match@1.0.0 
  │ │   └── concat-map@0.0.1 
  │ └── path-is-absolute@1.0.1 
  ├─┬ handlebars@4.0.10 
  │ ├─┬ optimist@0.6.1 
  │ │ ├── minimist@0.0.10 
  │ │ └── wordwrap@0.0.3 
  │ ├── source-map@0.4.4 
  │ └─┬ uglify-js@2.8.29 
  │   ├── source-map@0.5.6 
  │   ├── uglify-to-browserify@1.0.2 
  │   └─┬ yargs@3.10.0 
  │     ├── camelcase@1.2.1 
  │     ├─┬ cliui@2.1.0 
  │     │ ├─┬ center-align@0.1.3 
  │     │ │ ├─┬ align-text@0.1.4 
  │     │ │ │ ├─┬ kind-of@3.2.2 
  │     │ │ │ │ └── is-buffer@1.1.5 
  │     │ │ │ ├── longest@1.0.1 
  │     │ │ │ └── repeat-string@1.6.1 
  │     │ │ └── lazy-cache@1.0.4 
  │     │ ├── right-align@0.1.3 
  │     │ └── wordwrap@0.0.2 
  │     ├── decamelize@1.2.0 
  │     └── window-size@0.1.0 
  ├─┬ js-yaml@3.9.0 
  │ ├─┬ argparse@1.0.9 
  │ │ └── sprintf-js@1.0.3 
  │ └── esprima@4.0.0 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├── nopt@3.0.6 
  ├─┬ once@1.4.0 
  │ └── wrappy@1.0.2 
  ├── resolve@1.1.7 
  ├─┬ supports-color@3.2.3 
  │ └── has-flag@1.0.0 
  ├─┬ which@1.2.14 
  │ └── isexe@2.0.0 
  └── wordwrap@1.0.0 

ॐ  ~/development/molecule/frontend topic/js-code-coverage! ☠ ember install ember-cli-code-coverage
Yarn: Installed ember-cli-code-coverage
Installed addon package.
```